# Generated by Django 6.0.7 on 2026-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force'), ('404_FLOOD', '404 Flood'), ('PATH_SCAN', 'Path Scan'), ('SUSPICIOUS_AGENT', 'Suspicious Agent')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('timestamp', models.CharField(db_index=True, max_length=30)),
                ('count', models.IntegerField(default=1)),
                ('status_code', models.IntegerField(default=200)),
                ('description', models.TextField()),
                ('paths', models.JSONField(blank=True, default=list)),
                ('raw_lines', models.JSONField(blank=True, default=list)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Anomaly',
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-created_at'],
            },
        ),
    ]
